### PR TITLE
 Add missing dependencies faad2, libmad and libmpeg2

### PR DESCRIPTION
**Pull request by Unrud**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
The _libmad_ module probably needs `"rm-configure": true` and `"config-opts": ["--disable-Werror" ]`.

**Comment by Unrud** [comment]
I've added the patches from Debian. `Provide-Thumb-2-alternative-code-for-MAD_F_MLN.diff` seems to deal with the problem.

> The _libmad_ module probably needs `"rm-configure": true`

Already doing this.

**Comment by Unrud** [comment]
bot, build

**Comment by Unrud** [comment]
bot, build

**Comment by AsciiWolf** [comment]
Same issue.

**Comment by Unrud** [comment]
> Same issue.

No, libmad compiles now.

**Comment by Unrud** [comment]
bot, build

**Comment by Unrud** [comment]
bot, build

**Comment by AsciiWolf** [comment]
> No, libmad compiles now.

Oops, you're right. :-)

**Comment by Unrud** [comment]
It finally compiles: https://flathub.org/builds/#/builders/2/builds/5029

**Pull request merged**
